"""unique metrics snapshot per day

Revision ID: 96280bb781b9
Revises: e013891656b9
Create Date: 2026-07-24 17:22:53.437863
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '96280bb781b9'
down_revision: Union[str, None] = 'e013891656b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_snapshot_day_source', 'metrics_snapshots', ['article_id', 'collected_at', 'source'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_snapshot_day_source', 'metrics_snapshots', type_='unique')
    # ### end Alembic commands ###
