"""job_runs tenant optional

Revision ID: e013891656b9
Revises: 3f47e4a154d9
Create Date: 2026-07-24 17:07:51.553158
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e013891656b9'
down_revision: Union[str, None] = '3f47e4a154d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_runs', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_runs', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
